### ISSUE TITLE
AttributeError: module 'rio_tiler.reader' has no attribute 'multi_metadata'

### ISSUE THREAD

**Issue by palmerj** [developmentseed/stac-viewer#3]
Running stac-viewer after pip install produces the following error:

```
$ stac-viewer
Traceback (most recent call last):
  File "/Users/jpalmer/Documents/Development/stac-viewer/.venv/bin/stac-viewer", line 11, in <module>
    load_entry_point('stac-viewer==0.0.1', 'console_scripts', 'stac-viewer')()
  File "/Users/jpalmer/Documents/Development/stac-viewer/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/jpalmer/Documents/Development/stac-viewer/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/Users/jpalmer/Documents/Development/stac-viewer/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Users/jpalmer/Documents/Development/stac-viewer/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/jpalmer/Documents/Development/stac-viewer/.venv/lib/python3.7/site-packages/stac_viewer-0.0.1-py3.7.egg/stac_viewer/scripts/cli.py", line 7, in <module>
    from stac_viewer import app, stac
  File "/Users/jpalmer/Documents/Development/stac-viewer/.venv/lib/python3.7/site-packages/stac_viewer-0.0.1-py3.7.egg/stac_viewer/app.py", line 13, in <module>
    from rio_viz.app import viz as BaseVizClass
  File "/Users/jpalmer/Documents/Development/stac-viewer/.venv/lib/python3.7/site-packages/rio_viz-0.2.3-py3.7.egg/rio_viz/app.py", line 13, in <module>
    from rio_viz.raster import postprocess_tile
  File "/Users/jpalmer/Documents/Development/stac-viewer/.venv/lib/python3.7/site-packages/rio_viz-0.2.3-py3.7.egg/rio_viz/raster.py", line 26, in <module>
    multi_meta = partial(run_in_threadpool, reader.multi_metadata)
AttributeError: module 'rio_tiler.reader' has no attribute 'multi_metadata'
```

**Comment by vincentsarago** [comment]
@palmerj yes this is due to latest rio-tiler update. 

stac-viewer deserve some update. right now you can force install of rio-tiler==2.0a11 to fix this issue
